### ISSUE TITLE
FPS floating point

### ISSUE THREAD

**Issue by japettyjohn** [OpenVisualCloud/SVT-VP9#38] opened 2019-06-11 23:58 UTC
I'm trying to encode a 29.97 fps source and have SVT output a 29.97 .ivf using fps-num 30000 and fps-denom 1001.  Everything looks correct while it is encoding, but when I then go to convert it to a webm with ffmpeg, I get an Invalid frame rate error, also when I try to use mediainfo with the .ivf file it doesn't allow me to see any of the metadata and only gives an Invalid floating point operation error.

I've tested the same workflow using fps 30 and it outputs fine, I can see the mediainfo on it and it will convert to webm.

I'm sure other people are outputting 29.97 and 23.976 properties so I'm trying to figure out what I'm doing wrong or if there is some other parameter that I am not thinking with that is required.

Command:

`SvtVp9EncApp.exe -i %sourcePath% -w 1920 -h 1080 -enc-mode 8 -fps-num 30000 -fps-denom 1001 -rc 1 -tbr 5000000 -intra-period 60 -b %destFile%`

**Comment by tianjunwork** [comment] 2019-06-12 19:13
Fixed in #40

**Comment by Sorqan** [comment] 2019-06-13 21:31
I added the changes and re-compiled, in testing I found that the output is now the correct fps at 29.970 and is working great.

But now when encoding with -fps 30 the output file comes out at 1.050 in the metadata, the bit-rate is oddly low and the runtime is very long.

**Comment by tianjunwork** [comment] 2019-06-14 03:48
@Sorqan I can't reproduce what you saw. Could post your command and statistics info during encoding for both 29.97 and 30 fps?

**Comment by Sorqan** [comment] 2019-06-14 04:26
@tianjunwork Here is the command I'm currently using respectively for 30fps and 29.97fps:

`SvtVp9EncApp.exe -i %sourcePath% -w 480 -h 270 -enc-mode 8 -fps-num 30000 -fps-denom 1001 -rc 1 -tbr 5000000 -b `

`SvtVp9EncApp.exe -i %sourcePath% -w 480 -h 270 -enc-mode 8 -fps 30 -rc 1 -tbr 5000000 -b %destFile%`

Using Mediainfo on the .ivf that these output, I am getting:

For the 30fps file (this one crashed when I try to play it after converting to a webm):
```
General
Complete name                            : C:\Users\****.ivf
Format                                   : IVF
File size                                : 3.01 MiB

Video
Format                                   : VP90
Codec ID                                 : VP90
Width                                    : 480 pixels
Height                                   : 270 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 0.990 fps
Stream size                              : 3.01 MiB (100%)

```

And for the 29.97fps file:

```
General
Complete name                            : C:\Users\****.ivf
Format                                   : IVF
File size                                : 1.25 MiB

Video
Format                                   : VP90
Codec ID                                 : VP90
Width                                    : 480 pixels
Height                                   : 270 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 29.970 (30000/1001) fps
Stream size                              : 1.25 MiB (100%)
```

**Comment by tianjunwork** [comment] 2019-06-14 05:12
@Sorqan this resolution should be block if you apply #40 on top of master tip. Could you try multiple of 8 resolution and check fps?

**Comment by Sorqan** [comment] 2019-06-14 20:28
@tianjunwork Sorry about that, here are the MediaInfo results from a 1080i 29.97fps encode and a 1080i 30fps. Same command as above except for `-w 1920 -h 1080`


**29.97:**
```
General
Complete name                            : C:\Users\*****.ivf
Format                                   : IVF
File size                                : 19.3 MiB

Video
Format                                   : VP90
Codec ID                                 : VP90
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 29.970 (30000/1001) fps
Stream size                              : 19.3 MiB (100%)
```

**30:**
```
General
Complete name                            : C:\Users\*****.ivf
Format                                   : IVF
File size                                : 19.4 MiB

Video
Format                                   : VP90
Codec ID                                 : VP90
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 0.990 fps
Stream size                              : 19.4 MiB (100%)


```

**Comment by tianjunwork** [comment] 2019-06-14 21:00
Still can't reproduce what you saw "0.990" fps.
I am running on Ubuntu. But that should't affect.
./SvtVp9EncApp -i 1920x1080.yuv -w 1920 -h 1080 -enc-mode 8 -fps 30 -rc 1 -tbr 5000000 -b xxxx.ivf
Video
Format                                   : VP90
Codec ID                                 : VP90
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 30.000 FPS
Stream size                              : 5.03 MiB (100%)

**Comment by Sorqan** [comment] 2019-06-14 21:13
@tianjunwork Well if its working fine for you then I am not too worried about it, could've been something in compiling as well. What's more important for me anyway is that 29.97 is working so thank-you for the quick fix on that. I haven't tested 23.976 yet but I assume that will work now as well.

**Comment by tianjunwork** [comment] 2019-06-14 21:41
@Sorqan Thank you for verifying the PR. Glad to help.

**Closed** 2019-06-19 23:57 UTC
Labels: bug
