### ISSUE TITLE
Shared lib executable stack

### ISSUE THREAD

**Issue by Vascom** [OpenVisualCloud/SVT-VP9#52] opened 2019-09-13 07:04 UTC
Compiled shared lib has warning from rpmlint:

The binary declares the stack as executable.  Executable stack is usually an
error as it is only needed if the code contains GCC trampolines or similar
constructs which uses code on the stack.  One common source for needlessly
executable stack cases are object files built from assembler files which don't
define a proper .note.GNU-stack section.

Solve it please.

**Comment by Austin-Hu** [comment] 2019-09-18 22:22
The issue can be fixed by PR #57 , and please also help verify it in your side, @Vascom. Thanks!

According to the [guidance](https://wiki.gentoo.org/wiki/Hardened/GNU_stack_quickstart), the basic addressing process is:
1. Run "readelf -lW libSvtVp9Enc.so.1 | grep GNU_STACK" to check whether there is "E" (executable), like this:
  GNU_STACK      0x000000 0x0000000000000000 0x0000000000000000 0x000000 0x000000 RWE 0x10
2. Per the statements [here](https://wiki.gentoo.org/wiki/Hardened/GNU_stack_quickstart)(_When you compile source code normally, gcc takes care of adding the GNU_STACK markings so that the final object code is not marked with an executable stack unless it actually needs it. However, if you compile assembly code, gcc will not automatically add GNU_STACK markings. So, the most common source of executable stacks in ELF binaries are packages which include raw assembly code._), the issue should be caused by the assembly files.
3. Use the [scanelf](https://github.com/gentoo/pax-utils) tool, to check which compiled object files don't set the .note.GNU-stack section.
4. Fix those filtered files one by one.
5. Clean, rebuild the project and run "readelf" again to check whether "E" disappears or not.

**Comment by Vascom** [comment] 2019-09-19 06:17
Verified.
Now good.

**Closed** 2019-09-21 01:09 UTC
Labels: Clean up
