### ISSUE TITLE
FFMPEG usage is crashing

### ISSUE THREAD

**Issue by cabirdme** [OpenVisualCloud/SVT-VP9#12] opened 2019-02-21 21:26 UTC
this usage leads to seg fault ( as guided by https://github.com/OpenVisualCloud/SVT-VP9/blob/master/ffmpeg_plugin/README.md ) :
 
ffmpeg -i Sintel.2010.1080p.mkv -c:v libsvt_vp9 -y output.mp4

Maybe another input could be used.  Mine was obtained from: https://durian.blender.org/download/ or http://ftp.nluug.nl/pub/graphics/blender/demo/movies/Sintel.2010.1080p.mkv ( i think ).

I'm attaching a backtrace of the crash - sorry I guess debug was not enabled.
[vp9.segfault.txt](https://github.com/OpenVisualCloud/SVT-VP9/files/2891322/vp9.segfault.txt)

**Comment by cabirdme** [comment] 2019-02-21 22:08
[vp9.segfault.txt](https://github.com/OpenVisualCloud/SVT-VP9/files/2891487/vp9.segfault.txt)

might be a better backtrace.

**Comment by hassount** [comment] 2019-02-23 23:50
@jsunintel

**Comment by jsunintel** [comment] 2019-02-25 06:51
I don't have this Sintel.2010.1080p.mkv. I tried a cmdline like below and can't reproduce any segfault.

ffmpeg -video_size 1920x1080 -pixel_format yuv420p -f rawvideo -i video_1920x1080_5frames.yuv -c:v libsvt_vp9 -y output.mp4

**Comment by jsunintel** [comment] 2019-02-26 09:52
[]# ./SvtVp9EncApp -i input.yuv -w 1920 -h 818 -b output.mp4
-------------------------------------
SVT-VP9 Encoder v0.1.0
SVT [version]   : SVT-VP9 Encoder Lib v0.1.0
SVT [build]     : GCC 5.4.0      64 bit
LIB Build date: Feb 25 2019 15:08:39
-------------------------------------------
Number of logical cores available: 8
Number of PPCS 75
-------------------------------------------
SVT [config]: Profile [0]       Level (auto)
SVT [config]: EncoderMode / Tune                                                : 9 / 1
SVT [config]: EncoderBitDepth                                                   : 8
SVT [config]: SourceWidth / SourceHeight                                        : 1920 / 820
SVT [config]: FrameRate / Gop Size                                              : 60 / 64
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 4 / 0 / 2
SVT [config]: BRC Mode / QP                                                     : CQP / 45
-------------------------------------------


Encoding        21Segmentation fault (core dumped)

[]# ./SvtVp9EncApp -i input.yuv -w 1920 -h 820 -b output.mp4
-------------------------------------
SVT-VP9 Encoder v0.1.0
SVT [version]   : SVT-VP9 Encoder Lib v0.1.0
SVT [build]     : GCC 5.4.0      64 bit
LIB Build date: Feb 25 2019 15:08:39
-------------------------------------------
Number of logical cores available: 8
Number of PPCS 75
-------------------------------------------
SVT [config]: Profile [0]       Level (auto)
SVT [config]: EncoderMode / Tune                                                : 9 / 1
SVT [config]: EncoderBitDepth                                                   : 8
SVT [config]: SourceWidth / SourceHeight                                        : 1920 / 820
SVT [config]: FrameRate / Gop Size                                              : 60 / 64
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 4 / 0 / 2
SVT [config]: BRC Mode / QP                                                     : CQP / 45
-------------------------------------------


Encoding        21Segmentation fault (core dumped)

**Comment by tianjunwork** [comment] 2019-02-26 21:52
Duplicated with #7

**Comment by EwoutH** [comment] 2019-05-20 08:46
@tianjunwork Any possibility to assign someone to this bug?

**Comment by tianjunwork** [comment] 2019-05-20 16:16
Hi @jsunintel, could you make this issue and vp9 bitstream compatibility your next priority?

**Comment by jsunintel** [comment] 2019-05-22 02:07
> vp9 bitstream compatibility

It’s about not-supported width/height combinations. It’s addressed by me. Please contact Hassene if they have time to add supports to not 8-aligned width/height.
And I don’t think it is a good thing to track another different issue (vp9 bitstream compatibility) in it. Please use the one with my debugging analysis for the vp9 bitstream compatibility issue.

**Comment by tianjunwork** [comment] 2019-05-22 03:25
@hassount, VP9 blocks non-8-aligned width/height 10-bit input. It crashes for non-8-aligned width/height 8-bit.
Does AV1 support non-8-aligned width/height 8-bit input? If so, porting can be planed.
Otherwise, a PR will be made to block 8-bit also.

**Comment by hassount** [comment] 2019-05-22 05:53
@tianjunwork 
Only SVT-HEVC supports non multiple of 8 resolutions. The change is not as easy as porting a fix as it depends on the buffers that are not aligned. I expect support for VP9 would be easier than AV1

**Comment by issaelaltero** [comment] 2019-05-30 21:56
See #35 Pull Request.

**Closed** 2019-06-13 14:36 UTC
Labels: bug, duplicate
